name: Build and Deploy Widget

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: react/package-lock.json
        
    - name: Install dependencies
      run: |
        cd react
        npm ci
        
    - name: Build widget
      run: |
        cd react
        npm run build-widget
        
    - name: Copy built files and demo to docs folder
      run: |
        mkdir -p docs
        cp react/dist/* docs/
        cp react/public/demo.html docs/
        # Update demo.html paths for GitHub Pages deployment
        sed -i 's|../dist/style.css|./style.css|g' docs/demo.html
        sed -i 's|../dist/magic-widget.umd.js|./magic-widget.umd.js|g' docs/demo.html
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "🚀 Auto-deploy: Build and update widget files
        
        - Built from commit: ${{ github.sha }}
        - Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        - Workflow: ${{ github.workflow }}"
        git push
